# Use Maven to build the application
FROM maven:3.8.4-openjdk-11 AS build
RUN mvn clean package -DskipTests

# Copy the compiled Spring Boot JAR file from the build stage
COPY --from=build /app/target/uploadify-backend.jar /app/uploadify-backend.jar

# Expose the port that the application will run on
EXPOSE 8080

# Define the entry point of the application
RUN mvn spring-boot:run
